In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
AllDHSsubclustersTable = pd.read_csv('2017-11-07SubClusterCenters.csv', header=None, sep='\t')

In [7]:
AllDHSsubclusters = AllDHSsubclustersTable.values[:,3:]

In [8]:
AllDHSsubclusters.shape

(183, 16)

In [11]:
SpecificDHSsubclustersTable = np.loadtxt('2018-01-04subcluster_centers.txt')

In [12]:
SpecificDHSsubclustersTable.shape

(69, 19)

In [13]:
SpecificDHSsubclusters = SpecificDHSsubclustersTable[:,3:]

In [14]:
SpecificDHSsubclusters.shape

(69, 16)

In [15]:
from scipy.spatial.distance import cdist 

In [16]:
foggybottom = cdist(AllDHSsubclusters, SpecificDHSsubclusters, metric='cosine' )

In [18]:
foggybottom.shape

(183, 69)

In [19]:
np.argmin(foggybottom, axis=0)

array([165, 131,  41,  74, 153,  73, 154,  50, 103, 105,  43,   7,   6,
        74,  53,  17,   8, 150, 143,  18, 165, 162, 142, 175,  38,  79,
        47,  72,  78,  14, 108, 102, 100, 164,  75, 164, 162,  85,  31,
       121,  92,  45,  54,  44,  45,  43,  45,  93,  99, 175, 167, 152,
        97,  65, 106,  93, 153, 167, 177,  12, 127,  49, 104,  57, 158,
       115,   0,  53, 176])

In [20]:
np.min(foggybottom, axis=0)

array([  1.83680989e-01,   2.06933547e-05,   1.02370207e-04,
         2.11737777e-02,   7.51810994e-03,   3.87748779e-02,
         1.61604267e-04,   1.58428950e-03,   4.98129520e-02,
         2.13690617e-02,   1.62167273e-03,   2.07791728e-03,
         4.25262309e-02,   2.88488921e-02,   7.37125700e-02,
         2.03963584e-07,   2.04580654e-02,   8.52511042e-04,
         7.47347609e-04,   5.30821984e-06,   4.81136309e-02,
         9.05457014e-03,   4.61684252e-06,   3.03070382e-03,
         1.39434310e-03,   2.61018253e-02,   3.49534288e-03,
         2.00981621e-02,   6.70221485e-02,   6.59417765e-06,
         4.91616692e-02,   3.28353242e-04,   2.04168396e-05,
         8.98160245e-04,   6.55486871e-02,   1.61420403e-01,
         4.16169096e-02,   4.16102280e-02,   4.52063115e-04,
         1.30835270e-03,   1.08635512e-03,   4.93602562e-04,
         1.27892452e-01,   1.21578971e-02,   1.18336493e-03,
         2.44371291e-03,   4.00532294e-03,   1.47934975e-02,
         4.81591264e-04,

In [21]:
len(list(set(np.argmin(foggybottom, axis=0))))

57

In [22]:
AllDHSsubclustersTable.shape

(183, 19)

In [32]:
AllDHSsubclustersTable[[0, 1, 2]].values[np.argmin(foggybottom, axis=0)]

array([[   32,     5,   726],
       [   26,     2, 16724],
       [    9,     1, 28973],
       [   16,     1, 19791],
       [   30,     2,  7619],
       [   15,     6,  6164],
       [   30,     3, 23614],
       [   11,     4,  1914],
       [   21,     1,  7789],
       [   21,     3,  7622],
       [   10,     1, 30130],
       [    2,     6,  8418],
       [    2,     5,  5630],
       [   16,     1, 19791],
       [   12,     3,  7761],
       [    5,     1, 83470],
       [    3,     1, 20672],
       [   29,     4,  3472],
       [   28,     3,  9104],
       [    5,     2,  9763],
       [   32,     5,   726],
       [   32,     2,  4034],
       [   28,     2, 29575],
       [   35,     1, 18925],
       [    8,     4,  5394],
       [   16,     6, 14479],
       [   11,     1,  8666],
       [   15,     5, 21219],
       [   16,     5,  7374],
       [    4,     1, 83765],
       [   21,     6, 17495],
       [   20,     5,  6646],
       [   20,     3, 10956],
       [  

In [33]:
AllDHSsubclustersTable.shape

(183, 19)

In [34]:
AllDHSsubclustersTable

0   1      2         3         4         5             6         7   \
0     1   1  27285  0.017768  0.017093  0.000793  6.552842e-02  0.009488   
1     1   2  12967  0.004446  0.007946  0.001783  1.271791e-02  0.004542   
2     2   1   7075  0.012594  0.005696  0.000972  1.209355e-02  0.027760   
3     2   2  16933  0.036199  0.028046  0.004753  6.782319e-02  0.034931   
4     2   3   4576  0.011102  0.011504  0.010621  1.051426e-02  0.017897   
5     2   4  17578  0.033097  0.011307  0.012662  2.839167e-02  0.027321   
6     2   5   5630  0.016174  0.006039  0.001372  1.056400e-02  0.299291   
7     2   6   8418  0.012152  0.003586  0.002564  1.635453e-03  0.004815   
8     3   1  20672  0.004583  0.002320  0.005127  2.579409e-03  0.054040   
9     3   2  19071  0.017184  0.065537  0.004857  3.023997e-02  0.008971   
10    3   3  18646  0.002159  0.005210  0.000695  1.999139e-02  0.010990   
11    3   4   4012  0.002289  0.005456  0.001085  3.509888e-03  0.003745   
12    3   5  13082  0.000851  0.000632  0.268589  2.133219e-03  0.000731   
13    3   6  23882  0.015642  0.020650  0.026218  2.783794e-02  0.011376   
14    4   1  83765  0.000204  0.000487  0.000928  1.833113e-03  0.009506   
15    4   2  25152  0.005500  0.010750  0.002895  5.714164e-03  0.019039   
16    4   3   8963  0.000643  0.002130  0.001752  9.494256e-04  0.002888   
17    5   1  83470  0.000042  0.000074  0.000366  1.896387e-05  0.000057   
18    5   2   9763  0.000046  0.000337  0.000187  1.982278e-04  0.000078   
19    5   3    941  0.001873  0.000694  0.002955  2.195600e-04  0.000512   
20    5   4   5318  0.004273  0.000732  0.019784  3.846021e-03  0.009695   
21    5   5   1004  0.000086  0.126422  0.000462  1.439947e-04  0.000279   
22    5   6   2577  0.000058  0.000620  0.000426 -1.539567e-17  0.002213   
23    6   1   8200  0.060351  0.042173  0.058427  1.370227e-01  0.100766   
24    6   2   7241  0.041873  0.050031  0.006290  2.193504e-01  0.027635   
25    6   3  18627  0.051873  0.015639  0.169824  5.596303e-02  0.182382   
26    6   4   7610  0.043256  0.041530  0.030314  8.385016e-02  0.018209   
27    6   5   7259  0.072072  0.015498  0.008166  3.452280e-02  0.240355   
28    6   6  11558  0.091474  0.025443  0.008946  2.322111e-02  0.025986   
29    7   1  16449  0.009266  0.009597  0.003384  2.430679e-02  0.819685   
..   ..  ..    ...       ...       ...       ...           ...       ...   
153  30   2   7619  0.000335  0.125357  0.000646  9.640885e-04  0.000708   
154  30   3  23614  0.002040  0.014758  0.004118  1.055390e-03  0.003408   
155  30   4   5803  0.004034  0.004993  0.001141  5.466476e-03  0.002332   
156  31   1  11029  0.012193  0.010950  0.005416  1.640438e-02  0.607664   
157  31   2  10992  0.001501  0.007115  0.001069  1.737351e-03  0.624421   
158  31   3  43523  0.031937  0.017552  0.021226  2.143532e-02  0.625598   
159  31   4  10380  0.002815  0.007568  0.000534  3.140388e-03  0.601888   
160  31   5  25089  0.006854  0.004565  0.011122  2.643754e-03  0.653812   
161  32   1   3290  0.001782  0.000820  0.577472  1.831661e-02  0.000776   
162  32   2   4034  0.067226  0.005595  0.517336  2.090455e-01  0.002269   
163  32   3   1025  0.001017  0.000531  0.497309  3.820471e-03  0.079690   
164  32   4   2307  0.023158  0.000170  0.890573  4.658011e-02  0.000988   
165  32   5    726  0.003555  0.004127  0.524470  1.021659e-02  0.003019   
166  32   6   1780  0.002903  0.000388  0.424882  8.682784e-03  0.000625   
167  33   1  87769  0.000262  0.000621  0.001177  1.771259e-04  0.000705   
168  33   2  33033  0.004751  0.014123  0.004957  4.981642e-03  0.009184   
169  34   1   6740  0.011956  0.010870  0.004816  2.096555e-02  0.028378   
170  34   2   6500  0.005440  0.005270  0.001493  3.040546e-03  0.006870   
171  34   3   9503  0.012232  0.009161  0.000956  1.347320e-02  0.008648   
172  34   4   8721  0.003340  0.005541  0.000681  4.352039e-03  0.344136   
173  34   5  20962  0.016161  0.023375  0.003401  2.2

In [36]:
SpecificDHSsubclustersTable.shape

(69, 19)

In [37]:
SpecificDHSsubclustersTablePD = pd.DataFrame(SpecificDHSsubclustersTable)

In [38]:
SpecificDHSsubclustersTablePD.head()


0    1        2         3             4         5         6   \
0  1.0  1.0   1234.0  0.045229 -1.281137e-20  0.309984  0.112469   
1  1.0  2.0  11154.0  0.988488 -1.950293e-19  0.001682  0.002721   
2  1.0  3.0  14361.0  0.006785  1.557245e-06  0.012424  0.972904   
3  2.0  1.0   4839.0  0.003444  4.601125e-02  0.002573  0.001755   
4  2.0  2.0   9042.0  0.048998  1.153947e-01  0.000130  0.020323   

             7         8             9         10        11            12  \
0 -2.515349e-17  0.223397  1.602769e-02  0.000000  0.048093  0.000000e+00   
1  6.102835e-03  0.000192  4.554778e-06  0.000000  0.000059  0.000000e+00   
2  1.331693e-04  0.000010  1.611175e-07  0.000000  0.000049  0.000000e+00   
3  1.598201e-02  0.595041  4.820677e-03  0.004561  0.070454  8.804696e-04   
4  4.466364e-03  0.029104  6.065709e-03  0.071839  0.036936  2.681713e-07   

         13            14            15        16        17            18  
0  0.007750  1.344623e-06  2.117582e-21  0.185386  0.051652  9.925014e-06  
1  0.000010  3.692534e-21  2.887853e-20  0.000668  0.000074 -6.866261e-20  
2  0.000008  3.798413e-21  3.439959e-07  0.007623  0.000063 -1.418251e-19  
3  0.000400  1.964705e-03  4.639520e-03  0.000921  0.244126  2.426471e-03  
4  0.000398  2.646600e-03  3.194719e-03  0.000897  0.645816  1.378900e-02

In [39]:
np.sort(np.min(foggybottom, axis=0))

array([  2.03963584e-07,   4.61684252e-06,   5.30821984e-06,
         6.59417765e-06,   2.04168396e-05,   2.06933547e-05,
         3.50751541e-05,   3.88901647e-05,   6.32223611e-05,
         1.02370207e-04,   1.61604267e-04,   3.28353242e-04,
         4.52063115e-04,   4.81591264e-04,   4.93602562e-04,
         7.47347609e-04,   8.52511042e-04,   8.98160245e-04,
         1.08635512e-03,   1.18336493e-03,   1.30835270e-03,
         1.39434310e-03,   1.58428950e-03,   1.62167273e-03,
         2.05528049e-03,   2.07791728e-03,   2.44371291e-03,
         3.03070382e-03,   3.49534288e-03,   4.00532294e-03,
         5.13029968e-03,   7.51810994e-03,   7.87453958e-03,
         8.79472044e-03,   8.82824339e-03,   9.05457014e-03,
         9.84689350e-03,   1.14448464e-02,   1.21578971e-02,
         1.23827296e-02,   1.25084611e-02,   1.40504938e-02,
         1.47934975e-02,   2.00981621e-02,   2.04580654e-02,
         2.11737777e-02,   2.13690617e-02,   2.61018253e-02,
         2.88488921e-02,

So basically 63/69 of the system-exclusive DHS prototyeps have matches to original 183 prototypes

In [40]:
matches_of_systemDHS = AllDHSsubclustersTable[[0, 1, 2]].values[np.argmin(foggybottom, axis=0)]

In [41]:
SpecificDHSsubclustersTablePD['Gprototype'] = matches_of_systemDHS[:,0]

In [42]:
SpecificDHSsubclustersTablePD['Gsubcluster'] = matches_of_systemDHS[:,1]

In [43]:
SpecificDHSsubclustersTablePD

0    1        2             3             4             5  \
0    1.0  1.0   1234.0  4.522911e-02 -1.281137e-20  3.099843e-01   
1    1.0  2.0  11154.0  9.884876e-01 -1.950293e-19  1.681512e-03   
2    1.0  3.0  14361.0  6.784604e-03  1.557245e-06  1.242360e-02   
3    2.0  1.0   4839.0  3.443779e-03  4.601125e-02  2.573175e-03   
4    2.0  2.0   9042.0  4.899841e-02  1.153947e-01  1.299144e-04   
5    2.0  3.0   8662.0  3.147288e-02  5.379034e-02  1.860256e-05   
6    2.0  4.0  15636.0  2.281349e-03  1.814736e-02  3.959169e-03   
7    2.0  5.0   1282.0  3.822960e-01 -9.298118e-16  8.673617e-18   
8    2.0  6.0   1231.0  7.355904e-02  4.173626e-04  1.496199e-17   
9    3.0  1.0   3382.0  9.207706e-06  2.552679e-01 -2.385245e-16   
10   3.0  2.0  20580.0  1.369609e-03  1.282269e-03  4.872950e-03   
11   3.0  3.0   4030.0  2.905985e-03  4.185084e-04  4.103642e-05   
12   3.0  4.0   2443.0  7.524786e-03  3.153848e-02  1.278425e-02   
13   3.0  5.0    473.0  7.403967e-03 -5.551115e-17  2.985882e-02   
14   3.0  6.0   1819.0  1.845822e-01 -2.532696e-16  7.340514e-03   
15   4.0  1.0  67153.0  3.950833e-16  0.000000e+00  2.484539e-04   
16   4.0  2.0   1431.0  5.827365e-02  0.000000e+00  1.993594e-05   
17   4.0  3.0   3110.0  4.671163e-02  0.000000e+00  3.252167e-06   
18   4.0  4.0   2831.0 -1.101549e-16  0.000000e+00  4.620347e-05   
19   4.0  5.0   8666.0  4.479923e-16  0.000000e+00  2.663451e-03   
20   4.0  6.0    165.0  6.401511e-05  0.000000e+00  4.095763e-01   
21   5.0  1.0   4058.0  6.906874e-02  0.000000e+00  5.808345e-01   
22   5.0  2.0  26698.0  2.500588e-05  0.000000e+00  2.214781e-04   
23   6.0  1.0   3550.0  8.812395e-16  0.000000e+00  3.671817e-04   
24   6.0  2.0   3841.0  3.080661e-04  0.000000e+00  3.259751e-05   
25   6.0  3.0   2076.0  1.866892e-03  0.000000e+00  6.703981e-03   
26   6.0  4.0   4131.0  3.280379e-06  0.000000e+00  3.850093e-05   
27   6.0  5.0   1538.0  1.598742e-01  0.000000e+00  3.319957e-06   
28   6.0  6.0   1400.0  6.438467e-03  0.000000e+00  1.890938e-02   
29   7.0  1.0  71435.0  0.000000e+00  3.158091e-04  8.464457e-04   
..   ...  ...      ...           ...           ...           ...   
39   9.0  3.0  32996.0 -1.292369e-16  0.000000e+00  2.880890e-03   
40   9.0  4.0   8710.0  5.445818e-02  0.000000e+00  2.009441e-01   
41  10.0  1.0   3950.0  7.271973e-02  0.000000e+00  3.538836e-15   
42  10.0  2.0   1812.0  1.311451e-15  0.000000e+00  3.083877e-01   
43  10.0  3.0    727.0 -2.081668e-16  0.000000e+00  0.000000e+00   
44  10.0  4.0   1405.0  5.439007e-02  0.000000e+00  5.108432e-04   
45  10.0  5.0    346.0  2.429682e-02  0.000000e+00  4.200899e-02   
46  10.0  6.0     45.0  4.543202e-02  0.000000e+00  3.091648e-02   
47  11.0  1.0  10893.0  1.956665e-01 -1.265806e-17  1.843034e-02   
48  11.0  2.0   8203.0  1.514944e-04 -1.103176e-17  8.418383e-04   
49  11.0  3.0   2507.0  5.594730e-04  4.025101e-18  2.362190e-03   
50  11.0  4.0   1751.0  5.278738e-03  1.647626e-03  3.455403e-06   
51  11.0  5.0   1509.0 -2.775558e-16  9.351244e-19  1.396452e-16   
52  11.0  6.0   3469.0  2.150848e-01 -1.992221e-18  1.041153e-04   
53  12.0  1.0  36353.0  3.247060e-02  5.759837e-01  1.951972e-02   
54  12.0  2.0  12573.0  4.652588e-03  7.251752e-02  1.358416e-04   
55  12.0  3.0   9305.0  1.590216e-01  4.437386e-02  1.544328e-02   
56  12.0  4.0   7816.0  2.064806e-02  1.070868e-01  6.582746e-05   
57  13.0  1.0  64034.0  3.765163e-05  1.260114e-16  8.193524e-03   
58  13.0  2.0  15664.0  2.246589e-04 -1.746921e-17  1.677298e-01   
59  13.0  3.0  16880.0  3.565852e-05 -1.779447e-17  3.434072e-01   
60  13.0  4.0  47905.0  1.889122e-02  2.973222e-04  6.198942e-03   
61  13.0  5.0   4646.0  7.083530e-02 -6.776264e-18  1.934237e-03   
62  13.0  6.0   5193.0  2.925361e-02 -8.375462e-18  1.077704e-01   
63  14.0  1.0  19719.0  6.154442e-03  0.000000e+00  1.544931e-03   
64  14.0  2.0   5613.0  3.010776e-02  0.000000e+00  2.239056e-01   
65  14.0  3.0  16158.0  6.645684e-03  0.000000e+00  3.929847e-0

In [54]:
SpecificDHSsubclustersTablePD.columns = ['EXprototype', 'EXsubcluster', 'N']+['C'+str(i) for i in range(16)] + ['Gprototype' , 'Gsubcluster']

In [55]:
SpecificDHSsubclustersTablePD.head()

EXprototype  EXsubcluster        N        C0            C1        C2  \
0          1.0           1.0   1234.0  0.045229 -1.281137e-20  0.309984   
1          1.0           2.0  11154.0  0.988488 -1.950293e-19  0.001682   
2          1.0           3.0  14361.0  0.006785  1.557245e-06  0.012424   
3          2.0           1.0   4839.0  0.003444  4.601125e-02  0.002573   
4          2.0           2.0   9042.0  0.048998  1.153947e-01  0.000130   

         C3            C4        C5            C6     ...             C8  \
0  0.112469 -2.515349e-17  0.223397  1.602769e-02     ...       0.048093   
1  0.002721  6.102835e-03  0.000192  4.554778e-06     ...       0.000059   
2  0.972904  1.331693e-04  0.000010  1.611175e-07     ...       0.000049   
3  0.001755  1.598201e-02  0.595041  4.820677e-03     ...       0.070454   
4  0.020323  4.466364e-03  0.029104  6.065709e-03     ...       0.036936   

             C9       C10           C11           C12       C13       C14  \
0  0.000000e+00  0.007750  1.344623e-06  2.117582e-21  0.185386  0.051652   
1  0.000000e+00  0.000010  3.692534e-21  2.887853e-20  0.000668  0.000074   
2  0.000000e+00  0.000008  3.798413e-21  3.439959e-07  0.007623  0.000063   
3  8.804696e-04  0.000400  1.964705e-03  4.639520e-03  0.000921  0.244126   
4  2.681713e-07  0.000398  2.646600e-03  3.194719e-03  0.000897  0.645816   

            C15  Gprototype  Gsubcluster  
0  9.925014e-06          32            5  
1 -6.866261e-20          26            2  
2 -1.418251e-19           9            1  
3  2.426471e-03          16            1  
4  1.378900e-02          30            2  

[5 rows x 21 columns]

In [103]:
SpecificDHSsubclustersTablePD.to_csv('DHSprototype_comparison.csv', sep='\t')

In [57]:
SpecificDHSsubclustersTablePD['Match_score'] = np.min(foggybottom, axis=0)

In [58]:
SpecificDHSsubclustersTablePD.head()


EXprototype  EXsubcluster        N        C0            C1        C2  \
0          1.0           1.0   1234.0  0.045229 -1.281137e-20  0.309984   
1          1.0           2.0  11154.0  0.988488 -1.950293e-19  0.001682   
2          1.0           3.0  14361.0  0.006785  1.557245e-06  0.012424   
3          2.0           1.0   4839.0  0.003444  4.601125e-02  0.002573   
4          2.0           2.0   9042.0  0.048998  1.153947e-01  0.000130   

         C3            C4        C5            C6     ...                 C9  \
0  0.112469 -2.515349e-17  0.223397  1.602769e-02     ...       0.000000e+00   
1  0.002721  6.102835e-03  0.000192  4.554778e-06     ...       0.000000e+00   
2  0.972904  1.331693e-04  0.000010  1.611175e-07     ...       0.000000e+00   
3  0.001755  1.598201e-02  0.595041  4.820677e-03     ...       8.804696e-04   
4  0.020323  4.466364e-03  0.029104  6.065709e-03     ...       2.681713e-07   

        C10           C11           C12       C13       C14           C15  \
0  0.007750  1.344623e-06  2.117582e-21  0.185386  0.051652  9.925014e-06   
1  0.000010  3.692534e-21  2.887853e-20  0.000668  0.000074 -6.866261e-20   
2  0.000008  3.798413e-21  3.439959e-07  0.007623  0.000063 -1.418251e-19   
3  0.000400  1.964705e-03  4.639520e-03  0.000921  0.244126  2.426471e-03   
4  0.000398  2.646600e-03  3.194719e-03  0.000897  0.645816  1.378900e-02   

   Gprototype  Gsubcluster  Match_score  
0          32            5     0.183681  
1          26            2     0.000021  
2           9            1     0.000102  
3          16            1     0.021174  
4          30            2     0.007518  

[5 rows x 22 columns]

In [176]:
foggybottom.shape

(183, 69)

match up more G subclusters to each EX subcluster, check each one's system exclusivity. See which prototypes get left out. 

In [237]:
extendedSubclusterDF = []
unmatched_subcluster_list = []
for i,Specific_row in enumerate(foggybottom):
    winningS = np.argmin(Specific_row)
    minscore = np.min(Specific_row)
    
    print(list(SpecificDHSsubclustersTablePD.values[winningS].astype(int)[0:3]))
    print( list(AllDHSsubclustersTable.values[i][0:3]))
    newrow = list(AllDHSsubclustersTable.values[i][0:3]) + [minscore, names[winningS]] + list(SpecificDHSsubclustersTablePD.values[winningS].astype(int)[0:3])
    extendedSubclusterDF.append(newrow)


[15, 1, 14112]
[1.0, 1.0, 27285.0]
[15, 1, 14112]
[1.0, 2.0, 12967.0]
[10, 6, 45]
[2.0, 1.0, 7075.0]
[10, 3, 727]
[2.0, 2.0, 16933.0]
[10, 6, 45]
[2.0, 3.0, 4576.0]
[10, 5, 346]
[2.0, 4.0, 17578.0]
[3, 4, 2443]
[2.0, 5.0, 5630.0]
[3, 3, 4030]
[2.0, 6.0, 8418.0]
[4, 2, 1431]
[3.0, 1.0, 20672.0]
[11, 4, 1751]
[3.0, 2.0, 19071.0]
[4, 2, 1431]
[3.0, 3.0, 18646.0]
[13, 1, 64034]
[3.0, 4.0, 4012.0]
[13, 3, 16880]
[3.0, 5.0, 13082.0]
[13, 1, 64034]
[3.0, 6.0, 23882.0]
[7, 1, 71435]
[4.0, 1.0, 83765.0]
[7, 1, 71435]
[4.0, 2.0, 25152.0]
[7, 1, 71435]
[4.0, 3.0, 8963.0]
[4, 1, 67153]
[5.0, 1.0, 83470.0]
[4, 5, 8666]
[5.0, 2.0, 9763.0]
[4, 1, 67153]
[5.0, 3.0, 941.0]
[4, 1, 67153]
[5.0, 4.0, 5318.0]
[4, 1, 67153]
[5.0, 5.0, 1004.0]
[4, 1, 67153]
[5.0, 6.0, 2577.0]
[12, 3, 9305]
[6.0, 1.0, 8200.0]
[12, 2, 12573]
[6.0, 2.0, 7241.0]
[1, 1, 1234]
[6.0, 3.0, 18627.0]
[6, 3, 2076]
[6.0, 4.0, 7610.0]
[3, 5, 473]
[6.0, 5.0, 7259.0]
[6, 3, 2076]
[6.0, 6.0, 11558.0]
[9, 2, 147170]
[7.0, 1.0, 16449.0]
[9, 2

In [191]:
extendedSubclusterDF

[[1.0, 1.0, 27285.0, 0.0020552804934733659, 15, 1, 14112],
 [1.0, 2.0, 12967.0, 0.0093331806077615598, 15, 1, 14112],
 [2.0, 1.0, 7075.0, 0.14219063860538594, 10, 6, 45],
 [2.0, 2.0, 16933.0, 0.059073274307197776, 10, 3, 727],
 [2.0, 3.0, 4576.0, 0.12897451216054434, 10, 6, 45],
 [2.0, 4.0, 17578.0, 0.015366116834228838, 10, 5, 346],
 [2.0, 5.0, 5630.0, 0.04252623094404262, 3, 4, 2443],
 [2.0, 6.0, 8418.0, 0.0020779172807705582, 3, 3, 4030],
 [3.0, 1.0, 20672.0, 0.020458065404214687, 4, 2, 1431],
 [3.0, 2.0, 19071.0, 0.019894135446460015, 11, 4, 1751],
 [3.0, 3.0, 18646.0, 0.025242954076458379, 4, 2, 1431],
 [3.0, 4.0, 4012.0, 0.10872923073219254, 13, 1, 64034],
 [3.0, 5.0, 13082.0, 0.012508461069512866, 13, 3, 16880],
 [3.0, 6.0, 23882.0, 0.0034684544085089586, 13, 1, 64034],
 [4.0, 1.0, 83765.0, 6.5941776499212068e-06, 7, 1, 71435],
 [4.0, 2.0, 25152.0, 0.0022176278881945732, 7, 1, 71435],
 [4.0, 3.0, 8963.0, 0.015186968186504335, 7, 1, 71435],
 [5.0, 1.0, 83470.0, 2.0396358380025958

In [238]:
extendedSubclusterDF = np.array(extendedSubclusterDF)

In [193]:
np.sort(extendedSubclusterDF[:,3])

array([  2.03963584e-07,   4.61684252e-06,   5.30821984e-06,
         6.59417765e-06,   2.04168396e-05,   2.06933547e-05,
         3.50751541e-05,   6.32223611e-05,   1.02370207e-04,
         1.61604267e-04,   3.28353242e-04,   4.52063115e-04,
         4.81591264e-04,   4.93602562e-04,   7.47347609e-04,
         7.56435413e-04,   8.20137740e-04,   8.52511042e-04,
         8.79905519e-04,   8.98160245e-04,   1.08635512e-03,
         1.13718957e-03,   1.30835270e-03,   1.39434310e-03,
         1.52132964e-03,   1.58428950e-03,   1.62167273e-03,
         2.05528049e-03,   2.07791728e-03,   2.21762789e-03,
         2.24058003e-03,   2.90740839e-03,   3.03070382e-03,
         3.46845441e-03,   3.49534288e-03,   3.94219521e-03,
         4.75798291e-03,   5.13029968e-03,   5.17269244e-03,
         5.44391952e-03,   6.63362374e-03,   7.40601873e-03,
         7.50187053e-03,   7.51810994e-03,   7.87453958e-03,
         8.79472044e-03,   9.05457014e-03,   9.33318061e-03,
         1.05935222e-02,

In [194]:
len(extendedSubclusterDF[:,3][extendedSubclusterDF[:,3] > 0.1])

51

In [197]:
carzooks = []
for i in range(183):
    mystr = extendedSubclusterDF[:,4].astype(str)[i] + 's' + extendedSubclusterDF[:,5].astype(str)[i]
    carzooks.append(mystr)
    #list(extendedSubclusterDF[:,4].astype(str)) + 's'*183 +  extendedSubclusterDF[:,5].astype(str)

In [200]:
len(list(set(carzooks)))

61

In [204]:
carzooks = []
for i in range(183):
    if (extendedSubclusterDF[:,3][i]<0.1):
        mystr = extendedSubclusterDF[:,4].astype(int).astype(str)[i] + 's' + extendedSubclusterDF[:,5].astype(int).astype(str)[i]
        carzooks.append(mystr)
    #list(extendedSubclusterDF[:,4].astype(str)) + 's'*183 +  ext

In [205]:
len(list(set(carzooks)))

56

In [210]:
carzooks[0:4]

['15s1', '15s1', '10s3', '10s5']

In [209]:
pd.DataFrame(extendedSubclusterDF)

0    1        2             3     4    5         6
0     1.0  1.0  27285.0  2.055280e-03  15.0  1.0   14112.0
1     1.0  2.0  12967.0  9.333181e-03  15.0  1.0   14112.0
2     2.0  1.0   7075.0  1.421906e-01  10.0  6.0      45.0
3     2.0  2.0  16933.0  5.907327e-02  10.0  3.0     727.0
4     2.0  3.0   4576.0  1.289745e-01  10.0  6.0      45.0
5     2.0  4.0  17578.0  1.536612e-02  10.0  5.0     346.0
6     2.0  5.0   5630.0  4.252623e-02   3.0  4.0    2443.0
7     2.0  6.0   8418.0  2.077917e-03   3.0  3.0    4030.0
8     3.0  1.0  20672.0  2.045807e-02   4.0  2.0    1431.0
9     3.0  2.0  19071.0  1.989414e-02  11.0  4.0    1751.0
10    3.0  3.0  18646.0  2.524295e-02   4.0  2.0    1431.0
11    3.0  4.0   4012.0  1.087292e-01  13.0  1.0   64034.0
12    3.0  5.0  13082.0  1.250846e-02  13.0  3.0   16880.0
13    3.0  6.0  23882.0  3.468454e-03  13.0  1.0   64034.0
14    4.0  1.0  83765.0  6.594178e-06   7.0  1.0   71435.0
15    4.0  2.0  25152.0  2.217628e-03   7.0  1.0   71435.0
16    4.0  3.0   8963.0  1.518697e-02   7.0  1.0   71435.0
17    5.0  1.0  83470.0  2.039636e-07   4.0  1.0   67153.0
18    5.0  2.0   9763.0  5.308220e-06   4.0  5.0    8666.0
19    5.0  3.0    941.0  1.225227e-02   4.0  1.0   67153.0
20    5.0  4.0   5318.0  1.137190e-03   4.0  1.0   67153.0
21    5.0  5.0   1004.0  1.059352e-02   4.0  1.0   67153.0
22    5.0  6.0   2577.0  1.242243e-02   4.0  1.0   67153.0
23    6.0  1.0   8200.0  2.284583e-01  12.0  3.0    9305.0
24    6.0  2.0   7241.0  1.031472e-01  12.0  2.0   12573.0
25    6.0  3.0  18627.0  2.709197e-01   1.0  1.0    1234.0
26    6.0  4.0   7610.0  1.650417e-01   6.0  3.0    2076.0
27    6.0  5.0   7259.0  1.786068e-01   3.0  5.0     473.0
28    6.0  6.0  11558.0  1.108273e-01   6.0  3.0    2076.0
29    7.0  1.0  16449.0  1.521330e-03   9.0  2.0  147170.0
..    ...  ...      ...           ...   ...  ...       ...
153  30.0  2.0   7619.0  7.518110e-03   2.0  2.0    9042.0
154  30.0  3.0  23614.0  1.616043e-04   2.0  4.0   15636.0
155  30.0  4.0   5803.0  1.554487e-02   2.0  4.0   15636.0
156  31.0  1.0  11029.0  7.398989e-02   9.0  2.0  147170.0
157  31.0  2.0  10992.0  8.778788e-02   9.0  2.0  147170.0
158  31.0  3.0  43523.0  1.100801e-02   9.0  2.0  147170.0
159  31.0  4.0  10380.0  8.277584e-02   9.0  2.0  147170.0
160  31.0  5.0  25089.0  4.814311e-02   9.0  2.0  147170.0
161  32.0  1.0   3290.0  1.067298e-01  13.0  3.0   16880.0
162  32.0  2.0   4034.0  9.054570e-03   5.0  1.0    4058.0
163  32.0  3.0   1025.0  1.934083e-01   8.0  3.0     549.0
164  32.0  4.0   2307.0  8.981602e-04   8.0  3.0     549.0
165  32.0  5.0    726.0  4.811363e-02   4.0  6.0     165.0
166  32.0  6.0   1780.0  1.163389e-01  13.0  3.0   16880.0
167  33.0  1.0  87769.0  3.507515e-05  11.0  4.0    1751.0
168  33.0  2.0  33033.0  8.201377e-04  13.0  1.0   64034.0
169  34.0  1.0   6740.0  1.152153e-01   7.0  1.0   71435.0
170  34.0  2.0   6500.0  1.035122e-01   7.0  1.0   71435.0
171  34.0  3.0   9503.0  9.744940e-02   7.0  1.0   71435.0
172  34.0  4.0   8721.0  1.482837e-01   7.0  1.0   71435.0
173  34.0  5.0  20962.0  1.136768e-02   7.0  1.0   71435.0
174  34.0  6.0  14724.0  5.643380e-02   7.0  1.0   71435.0
175  35.0  1.0  18925.0  3.030704e-03   6.0  1.0    3550.0
176  35.0  2.0  13823.0  1.238273e-02  15.0  3.0    2384.0
177  36.0  1.0  13643.0  5.130300e-03  13.0  2.0   15664.0
178  36.0  2.0   4801.0  1.147200e-01   4.0  5.0    8666.0
179  36.0  3.0   5598.0  8.567426e-02   4.0  5.0    8666.0
180  36.0  4.0  20485.0  2.056235e-02   4.0  5.0    8666.0
181  36.0  5.0   3658.0  1.074623e-01  13.0  2.0   15664.0
182  36.0  6.0  16361.0  3.267938e-02   4.0  5.0    8666.0

[183 rows x 7 columns]

In [216]:
AllDHSsubclustersTable.values[:,3:].shape

(183, 16)

In [217]:
np.sum(AllDHSsubclustersTable.values[:,3:], axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [218]:
np.max(AllDHSsubclustersTable.values[:,3:], axis=1)

array([ 0.6501109 ,  0.89411913,  0.47381502,  0.38796665,  0.45233132,
        0.57922077,  0.49733856,  0.55411881,  0.68146394,  0.60451291,
        0.66252885,  0.60920808,  0.62167877,  0.75429364,  0.9711606 ,
        0.81566295,  0.8238409 ,  0.99681857,  0.89685941,  0.85209519,
        0.87659023,  0.86212216,  0.84264881,  0.13702274,  0.32147394,
        0.21466019,  0.30397475,  0.31719689,  0.31119961,  0.81968519,
        0.90988239,  0.91560998,  0.99075308,  0.83134212,  0.8491477 ,
        0.28383648,  0.33934042,  0.32791295,  0.43337637,  0.31510477,
        0.25771792,  0.95773654,  0.7452476 ,  0.94601586,  0.75408175,
        0.77995309,  0.79532765,  0.52216639,  0.35034613,  0.4331681 ,
        0.5241066 ,  0.32121036,  0.39196079,  0.33074859,  0.36946068,
        0.26850838,  0.34077742,  0.96169678,  0.76926421,  0.76927167,
        0.77012839,  0.76013857,  0.43549268,  0.50387738,  0.86397762,
        0.59792444,  0.47838467,  0.46611963,  0.58630179,  0.54

In [219]:
Homog1 = np.max(AllDHSsubclustersTable.values[:,3:], axis=1)

In [228]:
np.sort(np.sort(AllDHSsubclustersTable.values[:,3:], axis=1)[:,-2] + Homog1)

array([ 0.26967109,  0.35831251,  0.39704192,  0.399058  ,  0.4069519 ,
        0.41381628,  0.42749488,  0.44291855,  0.45107003,  0.45330639,
        0.47414064,  0.4796199 ,  0.48981432,  0.49124987,  0.50287377,
        0.51779715,  0.5241698 ,  0.52535121,  0.52823174,  0.53064466,
        0.54082433,  0.54311825,  0.55528244,  0.55755149,  0.57115196,
        0.57203395,  0.58072556,  0.58297871,  0.58303957,  0.58456075,
        0.58635698,  0.58863306,  0.59976087,  0.60082751,  0.60787205,
        0.61171048,  0.61426305,  0.62278317,  0.62444266,  0.62547015,
        0.62716649,  0.63433706,  0.63554772,  0.63577624,  0.63844171,
        0.6411542 ,  0.64342447,  0.64420931,  0.64592499,  0.65150654,
        0.65577344,  0.65713307,  0.65955476,  0.66927095,  0.6700495 ,
        0.67481268,  0.67612282,  0.67621086,  0.68201288,  0.68340008,
        0.68917047,  0.68974965,  0.69427591,  0.69926463,  0.70768824,
        0.70870444,  0.71646613,  0.72056819,  0.72255925,  0.72

In [229]:
np.sort(np.sort(AllDHSsubclustersTable.values[:,3:], axis=1)[:,-2] - Homog1)

array([-0.99572925, -0.98728926, -0.98653862, -0.96826135, -0.96815879,
       -0.96165451, -0.95102514, -0.95049565, -0.92757071, -0.92271609,
       -0.89710555, -0.87707172, -0.86837778, -0.85777113, -0.85539524,
       -0.84526869, -0.84399245, -0.83158307, -0.80935709, -0.79160677,
       -0.78662942, -0.74008261, -0.7376625 , -0.73590361, -0.73571436,
       -0.73570039, -0.73154641, -0.72338783, -0.72072665, -0.71753616,
       -0.70970934, -0.70053149, -0.69897456, -0.67968851, -0.67875623,
       -0.66801272, -0.66751375, -0.6627767 , -0.66088712, -0.63947888,
       -0.63912343, -0.6373171 , -0.62787284, -0.61449345, -0.60226225,
       -0.59947938, -0.59122186, -0.57992839, -0.57507321, -0.57368589,
       -0.55725182, -0.55237665, -0.54458994, -0.53897633, -0.53768871,
       -0.53565838, -0.52095075, -0.50625899, -0.49892474, -0.49130746,
       -0.48440641, -0.47928785, -0.4703293 , -0.45269059, -0.44414953,
       -0.4435669 , -0.431345  , -0.42609334, -0.42339464, -0.39

In [239]:
DFextendedSubclusterDF = pd.DataFrame(extendedSubclusterDF) 

In [240]:
DFextendedSubclusterDF.columns=[['Gprototype', 'Gsubcluster', 'GN', 'MatchScore', 'name_of_EX', 'EXprototype', 'EXsubcluster', 'EXN']]

In [241]:
DFextendedSubclusterDF['Dominant'] = np.max(AllDHSsubclustersTable.values[:,3:], axis=1)

In [242]:
DFextendedSubclusterDF['Secondary'] = np.sort(AllDHSsubclustersTable.values[:,3:], axis=1)[:,-2]

In [243]:
DFextendedSubclusterDF.head()

Gprototype Gsubcluster       GN        MatchScore             name_of_EX  \
0        1.0         1.0  27285.0  0.00205528049347  Respiratory_1,N=14112   
1        1.0         2.0  12967.0  0.00933318060776  Respiratory_1,N=14112   
2        2.0         1.0   7075.0    0.142190638605         Hepatic_6,N=45   
3        2.0         2.0  16933.0   0.0590732743072        Hepatic_3,N=727   
4        2.0         3.0   4576.0    0.128974512161         Hepatic_6,N=45   

  EXprototype EXsubcluster    EXN  Dominant Secondary  
0          15            1  14112  0.650111  0.076425  
1          15            1  14112  0.894119  0.025741  
2          10            6     45  0.473815  0.279551  
3          10            3    727  0.387967  0.103283  
4          10            6     45  0.452331  0.279553

In [254]:
DFextendedSubclusterDF

Gprototype Gsubcluster       GN         MatchScore  \
0          1.0         1.0  27285.0   0.00205528049347   
1          1.0         2.0  12967.0   0.00933318060776   
2          2.0         1.0   7075.0     0.142190638605   
3          2.0         2.0  16933.0    0.0590732743072   
4          2.0         3.0   4576.0     0.128974512161   
5          2.0         4.0  17578.0    0.0153661168342   
6          2.0         5.0   5630.0     0.042526230944   
7          2.0         6.0   8418.0   0.00207791728077   
8          3.0         1.0  20672.0    0.0204580654042   
9          3.0         2.0  19071.0    0.0198941354465   
10         3.0         3.0  18646.0    0.0252429540765   
11         3.0         4.0   4012.0     0.108729230732   
12         3.0         5.0  13082.0    0.0125084610695   
13         3.0         6.0  23882.0   0.00346845440851   
14         4.0         1.0  83765.0  6.59417764992e-06   
15         4.0         2.0  25152.0   0.00221762788819   
16         4.0         3.0   8963.0    0.0151869681865   
17         5.0         1.0  83470.0    2.039635838e-07   
18         5.0         2.0   9763.0  5.30821983602e-06   
19         5.0         3.0    941.0    0.0122522710736   
20         5.0         4.0   5318.0   0.00113718957029   
21         5.0         5.0   1004.0    0.0105935222451   
22         5.0         6.0   2577.0    0.0124224345315   
23         6.0         1.0   8200.0     0.228458321707   
24         6.0         2.0   7241.0     0.103147199939   
25         6.0         3.0  18627.0     0.270919703545   
26         6.0         4.0   7610.0     0.165041749801   
27         6.0         5.0   7259.0     0.178606765124   
28         6.0         6.0  11558.0     0.110827268162   
29         7.0         1.0  16449.0   0.00152132964285   
..         ...         ...      ...                ...   
153       30.0         2.0   7619.0   0.00751810994408   
154       30.0         3.0  23614.0  0.000161604266777   
155       30.0         4.0   5803.0    0.0155448714012   
156       31.0         1.0  11029.0    0.0739898943887   
157       31.0         2.0  10992.0    0.0877878837831   
158       31.0         3.0  43523.0    0.0110080131466   
159       31.0         4.0  10380.0    0.0827758413424   
160       31.0         5.0  25089.0    0.0481431082973   
161       32.0         1.0   3290.0     0.106729790255   
162       32.0         2.0   4034.0    0.0090545701394   
163       32.0         3.0   1025.0     0.193408317062   
164       32.0         4.0   2307.0  0.000898160245354   
165       32.0         5.0    726.0    0.0481136308911   
166       32.0         6.0   1780.0     0.116338860471   
167       33.0         1.0  87769.0  3.50751540793e-05   
168       33.0         2.0  33033.0  0.000820137739562   
169       34.0         1.0   6740.0      0.11521525105   
170       34.0         2.0   6500.0     0.103512166457   
171       34.0         3.0   9503.0    0.0974493965177   
172       34.0         4.0   8721.0     0.148283685422   
173       34.0         5.0  20962.0    0.0113676764176   
174       34.0         6.0  14724.0    0.0564337996317   
175       35.0         1.0  18925.0   0.00303070382452   
176       35.0         2.0  13823.0    0.0123827295918   
177       36.0         1.0  13643.0   0.00513029967689   
178       36.0         2.0   4801.0      0.11471996272   
179       36.0         3.0   5598.0    0.0856742587427   
180       36.0         4.0  20485.0    0.0205623535292   
181       36.0         5.0   3658.0     0.107462320979   
182       36.0         6.0  16361.0    0.0326793750868   

                     name_of_EX EXprototype EXsubcluster     EXN  Dominant  \
0         Respiratory_1,N=14112          15            1   14112  0.650111   
1         Respiratory_1,N=14112          15            1   14112  0.894119   
2                Hepatic_6,N=45          10            6      45  0.473815   
3               Hepatic_3,N=727          10            3     727  0.387967   
4                

In [245]:
today = get_today()

In [246]:
DFextendedSubclusterDF.to_csv(today+'Prototype_Matching.csv',sep='\t')

In [252]:
DFextendedSubclusterDF.columns

MultiIndex(levels=[['EXN', 'EXprototype', 'EXsubcluster', 'GN', 'Gprototype', 'Gsubcluster', 'MatchScore', 'name_of_EX', 'Dominant', 'Secondary']],
           labels=[[4, 5, 3, 6, 7, 1, 2, 0, 8, 9]])

In [253]:
DFextendedSubclusterDF.sort_values(by='Secondary')

NameError: name 'Secondary' is not defined

# interlude - wouter wants a bargraph plot showing all system-specific prototypes

In [59]:
from OONMFunOO import *

/Users/amuratov/anaconda/lib/python3.5/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


In [61]:
SpecificDHSsubclustersTablePD.EXprototype.values.astype(int).astype(str)

array(['1', '1', '1', '2', '2', '2', '2', '2', '2', '3', '3', '3', '3',
       '3', '3', '4', '4', '4', '4', '4', '4', '5', '5', '6', '6', '6',
       '6', '6', '6', '7', '7', '8', '8', '8', '8', '8', '8', '9', '9',
       '9', '9', '10', '10', '10', '10', '10', '10', '11', '11', '11',
       '11', '11', '11', '12', '12', '12', '12', '13', '13', '13', '13',
       '13', '13', '14', '14', '14', '15', '15', '15'], 
      dtype='<U21')

In [67]:
names = [SpecificDHSsubclustersTablePD.EXprototype.values.astype(int).astype(str)[i] +'sub' +SpecificDHSsubclustersTablePD.EXsubcluster.values.astype(int).astype(str)[i] for i in range(69)]

In [68]:
names

['1sub1',
 '1sub2',
 '1sub3',
 '2sub1',
 '2sub2',
 '2sub3',
 '2sub4',
 '2sub5',
 '2sub6',
 '3sub1',
 '3sub2',
 '3sub3',
 '3sub4',
 '3sub5',
 '3sub6',
 '4sub1',
 '4sub2',
 '4sub3',
 '4sub4',
 '4sub5',
 '4sub6',
 '5sub1',
 '5sub2',
 '6sub1',
 '6sub2',
 '6sub3',
 '6sub4',
 '6sub5',
 '6sub6',
 '7sub1',
 '7sub2',
 '8sub1',
 '8sub2',
 '8sub3',
 '8sub4',
 '8sub5',
 '8sub6',
 '9sub1',
 '9sub2',
 '9sub3',
 '9sub4',
 '10sub1',
 '10sub2',
 '10sub3',
 '10sub4',
 '10sub5',
 '10sub6',
 '11sub1',
 '11sub2',
 '11sub3',
 '11sub4',
 '11sub5',
 '11sub6',
 '12sub1',
 '12sub2',
 '12sub3',
 '12sub4',
 '13sub1',
 '13sub2',
 '13sub3',
 '13sub4',
 '13sub5',
 '13sub6',
 '14sub1',
 '14sub2',
 '14sub3',
 '15sub1',
 '15sub2',
 '15sub3']

In [69]:
systemlist = ['Cardiovascular', 'Connective', 'Digestive', 'Embryonic', 'Endocrine', 'Epithelial', 'FetalLifeSupport', 'Genitourinary', 'Hematopoietic', 'Hepatic', 'Intergumentary', 'Musculoskeletal', 'Nervous', 'Renal', 'Respiratory']

In [83]:
thenames = [systemlist[SpecificDHSsubclustersTablePD.EXprototype.values.astype(int)[i]-1] +'_' +SpecificDHSsubclustersTablePD.EXsubcluster.values.astype(int).astype(str)[i] + ',N='+SpecificDHSsubclustersTablePD.N.values.astype(int).astype(str)[i] for i in range(69)]

In [84]:
thenames

['Cardiovascular_1,N=1234',
 'Cardiovascular_2,N=11154',
 'Cardiovascular_3,N=14361',
 'Connective_1,N=4839',
 'Connective_2,N=9042',
 'Connective_3,N=8662',
 'Connective_4,N=15636',
 'Connective_5,N=1282',
 'Connective_6,N=1231',
 'Digestive_1,N=3382',
 'Digestive_2,N=20580',
 'Digestive_3,N=4030',
 'Digestive_4,N=2443',
 'Digestive_5,N=473',
 'Digestive_6,N=1819',
 'Embryonic_1,N=67153',
 'Embryonic_2,N=1431',
 'Embryonic_3,N=3110',
 'Embryonic_4,N=2831',
 'Embryonic_5,N=8666',
 'Embryonic_6,N=165',
 'Endocrine_1,N=4058',
 'Endocrine_2,N=26698',
 'Epithelial_1,N=3550',
 'Epithelial_2,N=3841',
 'Epithelial_3,N=2076',
 'Epithelial_4,N=4131',
 'Epithelial_5,N=1538',
 'Epithelial_6,N=1400',
 'FetalLifeSupport_1,N=71435',
 'FetalLifeSupport_2,N=1695',
 'Genitourinary_1,N=4787',
 'Genitourinary_2,N=10068',
 'Genitourinary_3,N=549',
 'Genitourinary_4,N=312',
 'Genitourinary_5,N=236',
 'Genitourinary_6,N=344',
 'Hematopoietic_1,N=27526',
 'Hematopoietic_2,N=147170',
 'Hematopoietic_3,N=32996

In [85]:
make_stacked_bar_plot(16, 69, SpecificDHSsubclusters.T, 'ClusterCenterPlots.pdf',names=np.array(thenames) )

In [102]:
len(names)

69

# interlude 2: find closest actual DHS to sample-specific subcluster centers

In [87]:
Mixture = np.load('2017-09-25NMF_Ncomps16Mixture.npy')
#should be 16 x 2.5e6
NormedMixture = Mixture / np.sum(Mixture, axis=0)

In [88]:
NormedMixture.shape

(16, 2232744)

In [89]:
SpecificDHSsubclusters.shape

(69, 16)

In [91]:
NormedMixture.T.shape

(2232744, 16)

In [92]:
closest_actual_DHS = cdist(SpecificDHSsubclusters, NormedMixture.T)

In [96]:
closest_actual_DHS_cosine = cdist(SpecificDHSsubclusters, NormedMixture.T, metric='cosine')

In [93]:
closest_actual_DHS.shape

(69, 2232744)

In [97]:
np.sort(np.min(closest_actual_DHS_cosine, axis=1))

array([ -2.22044605e-16,   2.22044605e-16,   2.15801482e-08,
         4.33873943e-08,   9.62398936e-08,   1.17852818e-07,
         1.99272407e-07,   8.97051218e-07,   2.30042646e-06,
         3.65668412e-06,   4.22962763e-06,   5.65440582e-06,
         1.03637849e-05,   1.19920447e-05,   1.67373817e-05,
         1.92546274e-05,   2.10747290e-05,   2.15772625e-05,
         2.16110798e-05,   2.44622632e-05,   3.05598710e-05,
         3.14177738e-05,   3.21994151e-05,   4.88718409e-05,
         5.47993857e-05,   5.73742126e-05,   7.41060007e-05,
         7.85192490e-05,   9.08919741e-05,   1.15284504e-04,
         1.18496213e-04,   1.82343760e-04,   1.84618763e-04,
         2.14955697e-04,   2.37478479e-04,   2.55049893e-04,
         2.83607775e-04,   3.68515858e-04,   4.16706840e-04,
         4.55344856e-04,   4.62651051e-04,   5.57984122e-04,
         7.08539709e-04,   9.12220042e-04,   9.57326992e-04,
         9.59839424e-04,   1.06929565e-03,   1.12708462e-03,
         1.17757468e-03,

In [99]:
np.argmin(closest_actual_DHS_cosine, axis=1)

array([ 600603, 1956516,   20608,  983222,  364598,   18859,   86405,
          6849, 1583818,    1695,  295680,  205842, 1779367,  114566,
          1007,  191581,    3479,     763, 1741991,    4451,  517258,
        351644,     107, 1608637,    1698,   12041,  184281, 1161183,
         11555,  947965,     587,     337,      67, 1225517,    6972,
         12802,    9829,  131277, 2144474, 2032671,    5158,     772,
          3777,    3560,    7949,     606,  286581,    4366, 1845637,
        631392,  518523,   18390,     216,  355210, 1887634,  648741,
       1524708,  602544,  964899,  979968, 2060910, 1445591,  118168,
       2162721,  784934, 1125672,  683675,   11814,    1878])

In [101]:
np.save('Quintessential_SSDHS.npy',np.argmin(closest_actual_DHS_cosine, axis=1))

# ok i have to redo it for system specificity

In [104]:
finname = 'systemlist.txt'
filelist = []
f = open(finname)
dars = f.readlines()
for line in dars:
    filelist.append(line.strip())
f.close()
    

In [105]:
Mixture.shape

(16, 2232744)

In [107]:
bigDHScut = np.zeros(Mixture.shape[1])
for i, thefile in enumerate(filelist):
    DHSCut = np.load(thefile)
    bigDHScut+=DHSCut

In [108]:
np.max(bigDHScut)

1.0

In [111]:
SSmixture = Mixture.T[bigDHScut.astype(bool)].T

In [113]:
NormedSSmixture = NormedMixture.T[bigDHScut.astype(bool)].T

In [112]:
SSmixture.shape

(16, 855256)

In [114]:
closest_actual_DHS_cosine = cdist(SpecificDHSsubclusters, NormedSSmixture.T, metric='cosine')

In [115]:
closest_actual_DHS_cosine.shape

(69, 855256)

In [164]:
np.argmin(closest_actual_DHS_cosine, axis=1)

array([ 32587, 372892,   7101, 369804, 101009,   6450, 253992,   2376,
         3307,    516, 547869,   1086,  57347,  42023,    303, 809881,
         1079,    210,    117,   1509, 283905,   1054,     35, 179942,
          518,   4158,    253,   2671,   3984, 100845,    163,     98,
           19, 308858,   2413,   4459,   3352,  48620, 573678, 773536,
         1819,    215,   1199,   1108,   2735,    166, 106756,   1475,
       167602,      8,  69818,   6285,     67, 131922,  39030, 113591,
        96740, 560204, 272607, 368717, 149692, 556099,   5937, 822632,
       295985, 425191, 258058,   4086,    558])

In [117]:
np.sort(np.min(closest_actual_DHS_cosine, axis=1))

array([ -2.22044605e-16,   2.22044605e-16,   2.15801482e-08,
         4.68637167e-08,   1.17852818e-07,   1.99272407e-07,
         8.97051218e-07,   2.30042646e-06,   4.22962763e-06,
         1.62486452e-05,   1.67373817e-05,   2.00869134e-05,
         2.03076222e-05,   2.05712253e-05,   2.10747290e-05,
         2.16110798e-05,   2.44622632e-05,   2.53497421e-05,
         2.60378011e-05,   3.05598710e-05,   3.14177738e-05,
         3.60396503e-05,   5.47993857e-05,   5.73742126e-05,
         5.93122990e-05,   7.85192490e-05,   9.08919741e-05,
         1.18496213e-04,   1.84618763e-04,   2.37478479e-04,
         2.55049893e-04,   2.55852635e-04,   2.70759398e-04,
         2.83607775e-04,   3.09733033e-04,   4.62651051e-04,
         5.57984122e-04,   6.52205515e-04,   7.08539709e-04,
         7.34189542e-04,   9.57326992e-04,   9.59839424e-04,
         1.05052978e-03,   1.06929565e-03,   1.12663242e-03,
         1.17757468e-03,   1.22560627e-03,   1.27294469e-03,
         1.43837473e-03,

### Fixed indexing error since first version

In [165]:
np.save('Quintessential_SSDHS_actualSS.npy',indsofinterest[bigDHScut.astype(bool)][np.argmin(closest_actual_DHS_cosine, axis=1)])

# now lets do it a third way to actually gaurantee that the quintessential lies in the right subcluster

In [119]:
subcluster_assignments = np.load('2018-01-04cluster_subcluster_assignments.npy')

In [120]:
subcluster_assignments.shape

(2232744, 2)

In [123]:
list_of_subclusters_prototypes = SpecificDHSsubclustersTablePD.EXprototype.values.astype(int)

In [124]:
list_of_subclusters_subclusters = SpecificDHSsubclustersTablePD.EXsubcluster.values.astype(int)

In [125]:
subcluster_assignments[0:10]

array([[ 6,  0],
       [12,  0],
       [-1, -1],
       [-1, -1],
       [-1, -1],
       [ 6,  0],
       [12,  3],
       [-1, -1],
       [-1, -1],
       [-1, -1]])

In [126]:
len((list_of_subclusters_prototypes))

69

In [128]:
NormedMixture.shape

(16, 2232744)

In [138]:
list_of_subclusters_prototypes

array([ 1,  1,  1,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  4,  4,
        4,  4,  4,  4,  5,  5,  6,  6,  6,  6,  6,  6,  7,  7,  8,  8,  8,
        8,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11,
       11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 14, 14, 14, 15, 15,
       15])

In [139]:
list_of_subclusters_subclusters

array([1, 2, 3, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2,
       1, 2, 3, 4, 5, 6, 1, 2, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 1, 2, 3, 4, 5,
       6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 1, 2, 3, 1, 2, 3])

In [143]:
indsofinterest = np.arange(NormedMixture.shape[1])

In [144]:
len(indsofinterest)

2232744

In [162]:

for i in range(69):
    cut = (subcluster_assignments[:,0] == list_of_subclusters_prototypes[i]-1) * (subcluster_assignments[:,1] == list_of_subclusters_subclusters[i]-1)
    #print(len(cut[cut]))
    #print(cdist(SpecificDHSsubclusters[i].reshape(1, 16), NormedMixture.T[cut]).shape)
    array_of_distances = cdist(SpecificDHSsubclusters[i].reshape(1, 16), NormedMixture.T[cut], metric='cosine')
    print(np.min(array_of_distances, axis=1))
    collection_of_inds.append(indsofinterest[cut][np.argmin(array_of_distances, axis=1)][0])
    

[ 0.11824104]
[  2.00869134e-05]
[  2.10747290e-05]
[ 0.00070854]
[ 0.00466778]
[ 0.01141834]
[ 0.00025585]
[ 0.00018462]
[ 0.01127296]
[  5.73742126e-05]
[  2.60378011e-05]
[  2.03076222e-05]
[ 0.03731397]
[ 0.00224561]
[ 0.00387454]
[  4.68637167e-08]
[ 0.0010693]
[ 0.00028361]
[ 0.00065221]
[  7.85192490e-05]
[ 0.00073419]
[ 0.00597254]
[  1.99272407e-07]
[ 0.00105053]
[ 0.00055798]
[ 0.00095733]
[ 0.00127294]
[ 0.00245342]
[ 0.00095984]
[  2.53497421e-05]
[  1.17852818e-07]
[  3.05598710e-05]
[  1.67373817e-05]
[  5.93122990e-05]
[ 0.00143837]
[ 0.0001185]
[  9.08919741e-05]
[ 0.00691482]
[  3.60396503e-05]
[ 0.00023748]
[ 0.00025505]
[  8.97051218e-07]
[ 0.]
[  2.30042646e-06]
[  4.22962763e-06]
[  2.15801481e-08]
[ 0.00046265]
[ 0.0057242]
[ 0.00027076]
[ 0.00030973]
[  3.22323837e-05]
[ -2.22044605e-16]
[  2.44622632e-05]
[ 0.00245641]
[ 0.00705112]
[ 0.07630201]
[ 0.00474477]
[  1.62486452e-05]
[ 0.00537999]
[ 0.00122561]
[ 0.00112663]
[ 0.05381988]
[ 0.01298107]
[  3.14177738e

In [157]:
collection_of_inds

[1518857,
 991385,
 20608,
 983222,
 271331,
 18859,
 673021,
 6849,
 9701,
 1695,
 1452396,
 3493,
 154570,
 114566,
 1007,
 2128462,
 3479,
 763,
 455,
 4451,
 752097,
 3384,
 107,
 482276,
 1698,
 12041,
 845,
 7704,
 11555,
 270776,
 587,
 337,
 67,
 820831,
 6972,
 12802,
 9829,
 131277,
 1515339,
 2032671,
 5158,
 772,
 3777,
 3560,
 7949,
 606,
 286581,
 4366,
 450529,
 26,
 3375,
 18390,
 216,
 355210,
 106915,
 306588,
 259727,
 1481708,
 132,
 979968,
 402416,
 744805,
 17434,
 2162721,
 784934,
 1125672,
 683675,
 11814,
 1878]

In [158]:
np.save('Quintessential_ExclusiveDHS.npy',np.array(collection_of_inds))

# now make 69 bed files for each subcluster

In [166]:
BigBed = pd.read_table('masterList.651samples.FDR0.0010.hg38.bed3', header=None)

In [167]:
BigBed.shape

(2232744, 3)

In [171]:
BigBed['indeces'] = indsofinterest

In [172]:
BigBed.head()

0      1      2  indeces
0  chr1  51868  52049        0
1  chr1  57273  57354        1
2  chr1  66364  66488        2
3  chr1  79102  79222        3
4  chr1  79452  79502        4

In [168]:
thenames = [systemlist[SpecificDHSsubclustersTablePD.EXprototype.values.astype(int)[i]-1] +'_' +SpecificDHSsubclustersTablePD.EXsubcluster.values.astype(int).astype(str)[i] + '_N_'+SpecificDHSsubclustersTablePD.N.values.astype(int).astype(str)[i] for i in range(69)]

In [169]:
thenames

['Cardiovascular_1_N_1234',
 'Cardiovascular_2_N_11154',
 'Cardiovascular_3_N_14361',
 'Connective_1_N_4839',
 'Connective_2_N_9042',
 'Connective_3_N_8662',
 'Connective_4_N_15636',
 'Connective_5_N_1282',
 'Connective_6_N_1231',
 'Digestive_1_N_3382',
 'Digestive_2_N_20580',
 'Digestive_3_N_4030',
 'Digestive_4_N_2443',
 'Digestive_5_N_473',
 'Digestive_6_N_1819',
 'Embryonic_1_N_67153',
 'Embryonic_2_N_1431',
 'Embryonic_3_N_3110',
 'Embryonic_4_N_2831',
 'Embryonic_5_N_8666',
 'Embryonic_6_N_165',
 'Endocrine_1_N_4058',
 'Endocrine_2_N_26698',
 'Epithelial_1_N_3550',
 'Epithelial_2_N_3841',
 'Epithelial_3_N_2076',
 'Epithelial_4_N_4131',
 'Epithelial_5_N_1538',
 'Epithelial_6_N_1400',
 'FetalLifeSupport_1_N_71435',
 'FetalLifeSupport_2_N_1695',
 'Genitourinary_1_N_4787',
 'Genitourinary_2_N_10068',
 'Genitourinary_3_N_549',
 'Genitourinary_4_N_312',
 'Genitourinary_5_N_236',
 'Genitourinary_6_N_344',
 'Hematopoietic_1_N_27526',
 'Hematopoietic_2_N_147170',
 'Hematopoietic_3_N_32996

In [173]:
for i in range(69):
    cut = (subcluster_assignments[:,0] == list_of_subclusters_prototypes[i]-1) * (subcluster_assignments[:,1] == list_of_subclusters_subclusters[i]-1)
    
    BigBed.loc[cut].to_csv(thenames[i]+'sites.bed3', header=False, index=False, sep='\t')

The original version of BigBed, I didnt add the extra column with index

In [174]:
for i in range(69):
    cut = (subcluster_assignments[:,0] == list_of_subclusters_prototypes[i]-1) * (subcluster_assignments[:,1] == list_of_subclusters_subclusters[i]-1)
    
    BigBed.loc[cut].to_csv(thenames[i]+'sites.bed4', header=False, index=False, sep='\t')